In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\usama\anaconda3\lib\site-packages (2.3.0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usama\anaconda3\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\usama\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usama\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\usama\anaconda3\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in c:\users\usama\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [14]:
import pandas as pd

# Load specific rows: 10 to 20 (zero-indexed, so this gets rows 10â€“19)
#df = pd.read_csv("pivot_evaluations.csv", skiprows=range(1, 10), nrows=10)
df = pd.read_csv("pivot_evaluations.csv")

# Display the result
#print(df)
df.shape

(964, 13)

In [15]:
df.columns

Index(['mbpp_id', 'run_01_pass', 'run_02_pass', 'run_03_pass', 'run_04_pass',
       'run_05_pass', 'run_06_pass', 'run_07_pass', 'run_08_pass',
       'run_09_pass', 'run_10_pass', 'run_11_pass', 'run_12_pass'],
      dtype='object')

In [16]:
def pass_at_k(n, c, k): 
  """ 
  :param n: total number of samples 
  :param c: number of correct samples 
  :param k: k in pass@$k$ 
  """ 
  if n - c < k: 
    return 1.0 
  return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1))

In [17]:
import pandas as pd
import numpy as np
# Your dataframe is named df
run_cols = [f'run_{i:02d}_pass' for i in range(1, 13)]
run_cols

['run_01_pass',
 'run_02_pass',
 'run_03_pass',
 'run_04_pass',
 'run_05_pass',
 'run_06_pass',
 'run_07_pass',
 'run_08_pass',
 'run_09_pass',
 'run_10_pass',
 'run_11_pass',
 'run_12_pass']

In [18]:
def compute_passk_row(row, k):
    values = row[run_cols]
    n = values.notna().sum()                     # number of valid samples
    c = values.astype(int).sum()                 # count of True = correct
    return pass_at_k(n, c, k)

# Add pass@1, pass@5, pass@10 columns
for k in [1, 5, 10]:
    df[f'pass@{k}'] = df.apply(lambda row: compute_passk_row(row, k), axis=1)

In [19]:
df

,mbpp_id,run_01_pass,run_02_pass,run_03_pass,run_04_pass,run_05_pass,run_06_pass,run_07_pass,run_08_pass,run_09_pass,run_10_pass,run_11_pass,run_12_pass,pass@1,pass@5,pass@10
0,11,False,False,True,False,False,False,False,False,False,False,False,True,0.166667,0.681818,0.984848
1,12,False,False,True,True,True,True,False,False,True,True,True,False,0.583333,0.998737,1.000000
2,13,False,False,False,False,False,False,False,False,False,False,False,False,0.000000,0.000000,0.000000
3,14,False,False,False,True,True,False,True,True,False,True,True,False,0.500000,0.992424,1.000000
4,15,False,False,False,False,False,False,False,False,False,False,False,False,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,970,True,True,True,True,True,True,True,True,True,True,True,True,1.000000,1.000000,1.000000
960,971,False,False,False,False,False,False,False,False,False,False,False,False,0.000000,0.000000,0.000000
961,972,False,True,False,False,True,False,False,False,True,True,True,False,0.416667,0.973485,1.000000
962,973,True,True,True,True,True,True,True,True,False,True,False,True,0.833333,1.000000,1.000000
963,974,False,True,True,True,True,False,True,False,False,True,False,True,0.583333,0.998737,1.000000

In [20]:
df[["mbpp_id", "pass@1", "pass@5", "pass@10"]].to_csv("pass@k.csv", index=False)